Repository ritwikshanker/GoCoronaGo, pull requests merged in 2020-10, with the labels that each got.

#25 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#26 added dark mode button
  app/build.gradle
  app/src/main/java/com/example/gocoronago/MainActivity.kt
  app/src/main/res/layout/switch_item.xml
  app/src/main/res/menu/menu_tracker.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#27 feat: add about screen
  app/src/main/java/com/example/gocoronago/MainActivity.kt
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/res/layout/about_fragment.xml
  app/src/main/res/menu/menu_tracker.xml
  app/src/main/res/values/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#28 updated about screen with new contributors
  app/src/main/res/layout/about_fragment.xml
Labels: hacktoberfest, hacktoberfest-accepted

#32 feat: add dynamic contributors
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/res/layout/about_fragment.xml
Labels: hacktoberfest, hacktoberfest-accepted

#33 PR Porting all Layouts from LinearLayout to ConstraintLayout
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainViewHolder.kt
  app/src/main/res/layout/about_fragment.xml
  app/src/main/res/layout/main_fragment.xml
Labels: hacktoberfest

#35 Added another contributor
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/java/com/example/gocoronago/stayHome/StayHomeActivity.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainRepo.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainViewModelFactory.kt
  app/src/main/res/xml/backup_descriptor.xml
Labels: documentation

#38 Theme choice will now be saved
  app/src/main/java/com/example/gocoronago/MainActivity.kt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#40 Issue #34: Made country spinner a searchable spinner.
  app/build.gradle
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/res/layout/main_fragment.xml
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#41 Issue/update icons
  app/src/main/java/com/example/gocoronago/stayHome/StayHomeFragment.kt
  app/src/main/res/drawable/ic_about.xml
  app/src/main/res/layout/about_fragment.xml
  app/src/main/res/raw/bat.json
  app/src/main/res/raw/sneeze_covid.json
  app/src/main/res/raw/stay_safe_stay_home.json
  app/src/main/res/values/strings.xml
Labels: bug, hacktoberfest, hacktoberfest-accepted

#43 #39-Add a option to select/change default country
  app/build.gradle
  app/src/main/java/com/example/gocoronago/extensions/SharedPrefExtensions.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 Brazilian portuguese translation
  app/src/main/java/com/example/gocoronago/stayHome/StayHomeFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/res/layout/stay_home.xml
  app/src/main/res/layout/switch_item.xml
  app/src/main/res/layout/total_cases.xml
  app/src/main/res/layout/total_cured.xml
  app/src/main/res/layout/total_death.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#45 #39-Add a option to select/change default country
  app/build.gradle
  app/src/main/java/com/example/gocoronago/extensions/SharedPrefExtensions.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#48 Add Czech translation
  app/src/main/res/values-cs-rCZ/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
