Repository ritwikshanker/GoCoronaGo, pull requests merged in 2021-10, with the labels that each got.

#61 Changed base API endpoint
  app/src/main/java/com/example/gocoronago/base/RetrofitInstance.kt
  app/src/main/java/com/example/gocoronago/homepage/models/WorldwideData.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainInterface.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainRepo.kt
Labels: enhancement

#62 Moved the About Us screen over to Jetpack Compose
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gocoronago/GoCoronaGoApplication.kt
  app/src/main/java/com/example/gocoronago/MainActivity.kt
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/java/com/example/gocoronago/about/model/Contributor.kt
  app/src/main/java/com/example/gocoronago/about/repository/AboutUsRepository.kt
  app/src/main/java/com/example/gocoronago/about/ui/AboutUsScreen.kt
  app/src/main/java/com/example/gocoronago/about/usecase/GetContributorListUseCase.kt
  app/src/main/java/com/example/gocoronago/about/usecase/GetVersionNameUseCase.kt
  app/src/main/java/com/example/gocoronago/about/viewmodel/AboutUsViewModel.kt
  app/src/main/java/com/example/gocoronago/di/AppModule.kt
  build.gradle
Labels: hacktoberfest, hacktoberfest-accepted, dependency, refactoring, technical debt

#63 Added Flipper for ease of development
  app/build.gradle
  app/src/debug/java/com/example/gocoronago/FlipperInitializer.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gocoronago/GoCoronaGoApplication.kt
  app/src/main/java/com/example/gocoronago/base/BaseRepo.kt
  app/src/main/java/com/example/gocoronago/base/RetrofitInstance.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/release/java/com.example.gocoronago/FlipperInitializer.java
Labels: hacktoberfest, hacktoberfest-accepted, dependency, developer

#66 Implemented loading and error screen on API errors
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/res/drawable/ic_surr_error.xml
  app/src/main/res/font/montserrat.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#52 v4.1
  .github/workflows/android.yml
  .idea/.gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/java/com/example/gocoronago/base/BaseFragment.kt
  app/src/main/java/com/example/gocoronago/homepage/CountriesItem.kt
  app/src/main/java/com/example/gocoronago/homepage/Global.kt
  app/src/main/java/com/example/gocoronago/homepage/Summary.kt
  app/src/main/java/com/example/gocoronago/stayHome/StayHomeActivity.kt
  app/src/main/java/com/example/gocoronago/stayHome/StayHomeFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainAdapter.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainDiffCallback.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainInterface.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainRepo.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainViewHolder.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/drawable/ic_surr_error.xml
  app/src/main/res/font/montserrat.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/layout/stay_home.xml
  app/src/main/res/layout/stay_home_vp.xml
  app/src/main/res/layout/switch_item.xml
  app/src/main/res/layout/total_cases.xml
  app/src/main/res/layout/total_cured.xml
  app/src/main/res/layout/total_death.xml
  app/src/main/res/values-cs-rCZ/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
