Repository ritwikshanker/GoCoronaGo, pull requests merged in 2022-10, with the labels that each got.

#77 Added Marathi strings
  app/src/main/res/values-mr/strings.xml
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#76 added translations for hindi language
  app/src/main/res/values-hi/strings.xml
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#78 Added French strings.
  app/src/main/res/values-fr/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#79 Upgraded gradle 7.3.1
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#82 added German strings.
  app/src/main/res/values-de/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#83 Translation/dutch
  app/src/main/res/values-nl/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#84 Translation/chinese
  app/src/main/res/values-zh/strings.xml
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#81 Updated various libraries
  app/build.gradle
  build.gradle
Labels: hacktoberfest, hacktoberfest-accepted, performance, refactoring, technical debt

#85 Target sdk and related changes
  app/build.gradle
  app/src/main/java/com/example/gocoronago/about/AboutFragment.kt
  app/src/main/java/com/example/gocoronago/ui/main/MainViewModelFactory.kt
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-zh/strings.xml
  build.gradle
Labels: hacktoberfest, hacktoberfest-accepted, dependency, developer, performance, refactoring, technical debt
